schema_version: 1

context:
  version: "0.0.6"
  python_min: "3.12"

package:
  name: scverse-misc
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/scverse-misc/scverse_misc-${{ version }}.tar.gz
  sha256: 3f6494998e9bc07d7abbe717ac46815943e1614565ebd21a3d0075d6580d43e8

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - session-info2
    - typing_extensions

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - scverse_misc
      pip_check: true

about:
  summary: Miscellaneous utility code used by scverse packages
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scverse/scverse-misc
  repository: https://github.com/scverse/scverse-misc
  documentation: https://scverse-misc.readthedocs.io/

extra:
  recipe-maintainers:
    - ilia-kats
    - flying-sheep
    - ilan-gold
    - grst
